name: Test, Build, and Deploy | Modul 01 Lab2.2 Senior Project
 
on:
  push:
    branches: [ main ]
 
jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Build app on VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          script: |
            eval "$(ssh-agent -s)"
            ssh-add ~./ssh/<<KEY_NAME_FROM_TA>>
            echo :Check project folder:;
            [ ! -d "${HOME}/senpro/<<NIU>>modul02/senpro-github-action/"] &&
             {
              echo "Repository has not bee cloned. Cloning...";
              mkdir -p ~senpro/<<NIU>>/modul02;
              cd ~/senpro/<<NIU>>/modul02;
              git clone <<FORM_REPOSITORY_LINK>>;
              cd ~/senpro/<<NIU>>/modul02/senpro-github-action;
              echo "Install Packages and Build Project";
              npm install;
              npm run build;
              } ||
               {
                echo "Repository already exists. Building...";
                cd ~/senpro/<<NIU>>/modul02/senpro-github-action;
                git restore .;
                git pull origin main;
                echo "Install Packages and Build Project";
                npm install;
                npm run build;
              }